FROM nginx:alpine

# 템플릿 파일 복사
COPY default.conf.template /tmp/default.conf.template

# 스크립트 복사 및 실행 권한 추가
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
