FROM nginx:alpine

# 템플릿 파일 복사
COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template

# entrypoint.sh를 올바른 위치로 복사
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# 실행 권한 추가
RUN chmod +x /usr/local/bin/entrypoint.sh

# ENTRYPOINT 설정
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
